# Generated by Django 5.1.4 on 2024-12-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("introduction", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Introduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("is_deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("video_url", models.URLField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "video_file",
                    models.FileField(blank=True, null=True, upload_to="videos/"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="carouselimage",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
