services:
  tet_gift_backend:
    build:
      context: ./backend
    container_name: tet_gift_backend
    image: tet_gift_backend
    environment:
      POSTGRES_DB: tet_gift
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_HOST: postgresql
      POSTGRES_PORT: 5432
      FRONTEND_URL: https://www.thuhanggift.store
    command: >
      sh -c "
      python manage.py migrate &&
      python create_samples/main.py &&
      daphne -b 0.0.0.0 -p 8000 backend.asgi:application
      "
    volumes:
      - backend_static:/app/static
      - backend_media:/app/media
    networks:
      - nginx_network
      - global_default


  tet_gift_frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: "https://backend.thuhanggift.store"
    image: tet_gift_frontend
    container_name: tet_gift_frontend
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
  global_default:
    external: true

volumes:
  backend_static:
  backend_media: