# Generated by Django 5.1.4 on 2024-12-12 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vessels", "0002_remove_vessel_capacity_remove_vessel_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PositionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "vessel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="vessels.vessel",
                    ),
                ),
            ],
        ),
    ]
