# Generated by Django 5.1.4 on 2024-12-23 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gifts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gift",
            name="price",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
