# Generated by Django 5.1.4 on 2024-12-16 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Tiêu đề")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NewsContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("text", "Chữ"),
                            ("image", "Hình ảnh"),
                            ("video", "Video"),
                        ],
                        max_length=10,
                        verbose_name="Loại nội dung",
                    ),
                ),
                (
                    "content_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="Nội dung chữ"
                    ),
                ),
                (
                    "content_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="news_images/",
                        verbose_name="Hình ảnh",
                    ),
                ),
                (
                    "content_video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="news_videos/",
                        verbose_name="Video",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Caption"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Thứ tự hiển thị"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="news.newspost",
                        verbose_name="Bài viết",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nội dung bài viết",
                "verbose_name_plural": "Các nội dung bài viết",
                "ordering": ["order"],
            },
        ),
    ]
