# Generated by Django 5.1.4 on 2024-12-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vessel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("registration_number", models.CharField(max_length=50, unique=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "captain_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "captain_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Hoạt động"),
                            ("inactive", "Không hoạt động"),
                            ("maintenance", "Bảo trì"),
                            ("warning", "Cảnh báo"),
                            ("sunk", "Chìm"),
                        ],
                        default="active",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("speed", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
