# Generated by Django 5.1.4 on 2024-12-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vessels", "0002_remove_vessel_capacity_remove_vessel_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vessel",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Hoạt động"),
                    ("inactive", "Không hoạt động"),
                    ("maintenance", "Maintenance"),
                ],
                default="active",
                max_length=50,
            ),
        ),
    ]
