# Generated by Django 5.1.4 on 2024-12-14 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vessels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrewMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Captain", "Captain"),
                            ("Engineer", "Engineer"),
                            ("Deckhand", "Deckhand"),
                            ("Cook", "Cook"),
                        ],
                        default="Deckhand",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("unit", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "vessel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crew",
                        to="vessels.vessel",
                    ),
                ),
            ],
        ),
    ]
