# Generated by Django 5.1.4 on 2024-12-12 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crew", "0001_initial"),
        ("vessels", "0002_remove_vessel_capacity_remove_vessel_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crewmember",
            name="age",
        ),
        migrations.RemoveField(
            model_name="crewmember",
            name="email",
        ),
        migrations.RemoveField(
            model_name="crewmember",
            name="joined_on",
        ),
        migrations.AddField(
            model_name="crewmember",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="crewmember",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="crewmember",
            name="unit",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="crewmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("Captain", "Captain"),
                    ("Engineer", "Engineer"),
                    ("Deckhand", "Deckhand"),
                    ("Cook", "Cook"),
                ],
                default="Deckhand",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="crewmember",
            name="vessel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crew",
                to="vessels.vessel",
            ),
        ),
    ]
